spring:
  application:
    name: VirtualPowerPlantSystem
  # h2 database config
  datasource:
    url: jdbc:h2:mem:virtual_power_plant_db
    driver-class-name: org.h2.Driver
    username: username
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /api/v1