spring:
  application:
    name: VirtualPowerPlantSystem
  # h2 database config
  datasource:
    url: jdbc:h2:mem:virtual_power_plant_db
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /api/v1